"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import type{AnswerId,ExamQuestion,ExamSession,SavedAttempt}from"../types/exam";
const CORRECT="תשובה נכונה, אבל ליהי גרוסמן אנגלצ׳ין פתרה את זה מהר יותר!!!";const WRONG="לוזר/ית, אפילו דני אנגלצ׳ין כבר יודעת מה התשובה";const SESSION="lihi-exam-session";const MISTAKES="lihi-exam-mistakes";
function mix<T>(items:T[]){return [...items].sort(()=>Math.random()-.5)}
export function ExamRunner({questions,title,sessionKey}:{questions:ExamQuestion[];title:string;sessionKey:string}){const [ready,setReady]=useState(false);const [index,setIndex]=useState(0);const [attempts,setAttempts]=useState<SavedAttempt[]>([]);const [selected,setSelected]=useState<AnswerId|null>(null);const [checked,setChecked]=useState(false);const [startedAt,setStartedAt]=useState(()=>Date.now());const [elapsedSeconds,setElapsedSeconds]=useState(1);const ordered=useMemo(()=>sessionKey.includes("random")?mix(questions):questions,[questions,sessionKey]);const current=ordered[index];
 useEffect(()=>{try{const raw=localStorage.getItem(SESSION);if(raw){const saved=JSON.parse(raw) as ExamSession;if(saved.key===sessionKey&&!saved.completedAt){const restoredIndex=Math.min(saved.index,ordered.length-1);const restoredAttempt=saved.attempts.find(attempt=>attempt.questionId===ordered[restoredIndex]?.id);setIndex(restoredIndex);setAttempts(saved.attempts);setStartedAt(saved.startedAt);if(restoredAttempt){setSelected(restoredAttempt.selected);setChecked(true)}}}}finally{setReady(true)}},[ordered,sessionKey]);
 useEffect(()=>{if(!ready||!ordered.length)return;localStorage.setItem(SESSION,JSON.stringify({key:sessionKey,title,questionIds:ordered.map(q=>q.id),index,attempts,startedAt} satisfies ExamSession))},[ready,index,attempts,ordered,sessionKey,startedAt,title]);
 if(!ready)return <div className="exam-loading">טוען את הבחינה…</div>;if(!current)return <div className="exam-empty"><h1>אין עדיין שאלות זמינות</h1><Link href="/exams">חזרה לכל המבחנים</Link></div>;
 function check(){if(!selected||checked)return;const attempt={questionId:current.id,selected,correct:selected===current.correctAnswer};setAttempts(a=>[...a,attempt]);setChecked(true)}
 function next(){if(index===ordered.length-1){const completed=[...attempts];const mistakes=completed.filter(a=>!a.correct).map(a=>a.questionId);const completedAt=Date.now();localStorage.setItem(MISTAKES,JSON.stringify(mistakes));localStorage.setItem(SESSION,JSON.stringify({key:sessionKey,title,questionIds:ordered.map(q=>q.id),index,attempts:completed,startedAt,completedAt}));setElapsedSeconds(Math.max(1,Math.round((completedAt-startedAt)/1000)));setIndex(ordered.length);return}setIndex(i=>i+1);setSelected(null);setChecked(false)}
 if(index>=ordered.length){const correct=attempts.filter(a=>a.correct).length;const wrong=attempts.filter(a=>!a.correct);return <section className="exam-results"><div className="result-score"><b>{Math.round(correct/ordered.length*100)}%</b><span>{correct} מתוך {ordered.length} תשובות נכונות</span></div><div className="result-stats"><div><b>{wrong.length}</b><span>תשובות שגויות</span></div><div><b>{Math.floor(elapsedSeconds/60)}:{String(elapsedSeconds%60).padStart(2,"0")}</b><span>זמן כולל</span></div></div>{wrong.length>0&&<div className="mistakes-list"><h2>השאלות שכדאי לתרגל שוב</h2>{wrong.map(a=>{const q=ordered.find(x=>x.id===a.questionId)!;return <article key={a.questionId}><b>{q.question}</b><p>התשובה הנכונה: <strong>{q.correctAnswer}. {q.options.find(o=>o.id===q.correctAnswer)?.text}</strong></p></article>})}</div>}<div className="result-actions">{wrong.length>0&&<Link href="/exams/run?mode=mistakes">תרגול הטעויות שלי</Link>}<Link href={`/exams/run?mode=year&value=${ordered[0].year}`}>מבחן חדש</Link><Link href="/exams">חזרה לכל המבחנים</Link></div></section>}
 return <section className="exam-runner"><header><div><small>{title}</small><b>שאלה {index+1} מתוך {ordered.length}</b></div><span>{Math.round((index/ordered.length)*100)}%</span></header><div className="exam-progress"><i style={{width:`${((index+1)/ordered.length)*100}%`}}/></div><article className="question-card"><div className="question-meta"><span>שאלה {current.questionNumber}</span><span>{current.topic}</span></div><h1>{current.question}</h1><div className="answer-list">{current.options.map(o=>{let state="";if(selected===o.id)state="selected";if(checked&&o.id===current.correctAnswer)state="correct";else if(checked&&selected===o.id)state="incorrect";return <button disabled={checked} className={state} key={o.id} onClick={()=>setSelected(o.id)}><b>{o.id}</b><span>{o.text}</span></button>})}</div>{checked&&<div className={`answer-feedback ${selected===current.correctAnswer?"right":"wrong"}`}>{selected===current.correctAnswer?CORRECT:WRONG}</div>}<div className="question-actions">{!checked?<button disabled={!selected} onClick={check}>בדיקת תשובה</button>:<button onClick={next}>{index===ordered.length-1?"סיום וקבלת ציון":"לשאלה הבאה"}</button>}</div></article></section>}
export const feedbackMessages={CORRECT,WRONG};
