/* eslint-disable react-hooks/exhaustive-deps */
"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
type Leader={display_name:string;best_score:number;total_attempts:number;best_average_time_ms:number;achieved_at:string;position?:number};
type Question={id:string;question:string;topic:string;options:{id:string;text:string}[];timeLimit:number;score:number};
type Result={message:string;score:number;totalTimeMs:number;averageTimeMs:number;personal:Leader&{position:number};question:string;selectedText?:string;correctAnswer:string;correctText:string;explanation?:string};
export function Leaderboard(){
  const[name,setName]=useState<string|null>(null),[leaders,setLeaders]=useState<Leader[]>([]),[personal,setPersonal]=useState<(Leader&{position:number})|null>(null),[configured,setConfigured]=useState(true),[error,setError]=useState(""),[question,setQuestion]=useState<Question|null>(null),[score,setScore]=useState(0),[time,setTime]=useState(30),[feedback,setFeedback]=useState(""),[result,setResult]=useState<Result|null>(null),[locked,setLocked]=useState(false);
  const questionRef=useRef<Question|null>(null),lockedRef=useRef(false);
  const refresh=useCallback(async()=>{const data=await(await fetch("/api/leaderboard")).json();setName(data.name);setLeaders(data.leaders);setPersonal(data.personal);setConfigured(data.configured)},[]);
  useEffect(()=>{const id=setTimeout(()=>void refresh(),0);return()=>clearTimeout(id)},[refresh]);
  async function login(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),response=await fetch("/api/leaderboard/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),code:form.get("code")})}),data=await response.json();if(!response.ok)return setError(data.error);setError("");await refresh()}
  async function loadQuestion(restart=false){const response=await fetch("/api/streak/question",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({restart})}),data=await response.json();if(!response.ok)return setError(data.error);questionRef.current=data;setQuestion(data);setScore(data.score);setTime(30);setFeedback("");lockedRef.current=false;setLocked(false)}
  async function start(){setResult(null);setError("");await loadQuestion(true)}
  const submit=useCallback(async(selected:string)=>{const current=questionRef.current;if(!current||lockedRef.current)return;lockedRef.current=true;setLocked(true);const response=await fetch("/api/streak/answer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionId:current.id,selected})}),data=await response.json();if(!response.ok){setError(data.error);return}setFeedback(data.message);if(data.correct){setScore(data.score);setTimeout(()=>void loadQuestion(false),850);return}questionRef.current=null;setQuestion(null);setResult(data);setPersonal(data.personal);await refresh()},[]);
  useEffect(()=>{if(!question||locked)return;const interval=setInterval(()=>setTime(value=>{if(value<=1){clearInterval(interval);void submit("");return 0}return value-1}),1000);return()=>clearInterval(interval)},[question,locked,submit]);
  if(!name)return <section className="leader-login"><span>מצטיין כיתתי</span><h1>כניסה למשחק הרצף</h1><form onSubmit={login}><label>שם הסטודנט/ית<input name="name" required/></label><label>קוד כניסה<input name="code" type="password" required inputMode="numeric"/></label>{error&&<p>{error}</p>}<button>כניסה</button></form></section>;
  return <><header className="leader-heading"><div><span>מחובר/ת: {name}</span><h1>מצטיין כיתתי</h1></div>{!question&&<button onClick={start}>התחלת משחק רצף</button>}</header>{!configured&&<p className="database-notice">יש להשלים את הגדרות Supabase כדי לשמור ניסיונות ולהציג דירוג.</p>}
  {question&&<section className="streak-game"><header><b>רצף נוכחי: {score} • שיא אישי: {personal?.best_score??0}</b><span>{time} שניות</span></header><h2>{question.question}</h2><div>{question.options.map(option=><button disabled={locked} key={option.id} onClick={()=>submit(option.id)}><b>{option.id}</b>{option.text}</button>)}</div>{feedback&&<p className="streak-feedback">{feedback}</p>}</section>}
  {result&&<section className="streak-end"><b>{result.message}</b><h2>הניקוד שלך: {result.score}</h2><p>השיא האישי שלך: {result.personal.best_score}</p><p>המיקום שלך: מקום {result.personal.position}</p><p>זמן כולל: {(result.totalTimeMs/1000).toFixed(1)} שניות</p><p>זמן ממוצע לשאלה: {(result.averageTimeMs/1000).toFixed(1)} שניות</p><p>מספר ניסיונות: {result.personal.total_attempts}</p><p>השאלה שבה נפסלת: {result.question}</p><p>התשובה שבחרת: {result.selectedText||"לא נבחרה תשובה"}</p><p>התשובה הנכונה: {result.correctAnswer}. {result.correctText}</p>{result.explanation&&<p>הסבר: {result.explanation}</p>}<div><button onClick={start}>נסי שוב</button><button onClick={()=>setResult(null)}>חזרה ללידרבורד</button><Link href="/practice">תרגול השאלה שטעיתי בה</Link></div></section>}
  <section className="leader-table"><table><thead><tr><th>מקום</th><th>שם</th><th>שיא</th><th>ניסיונות</th><th>זמן ממוצע בשיא</th><th>תאריך השיא</th></tr></thead><tbody>{leaders.slice(0,10).map((leader,index)=><tr className={leader.display_name===name?"current":""} key={leader.display_name}><td>{["🥇","🥈","🥉"][index]||index+1}</td><td>{leader.display_name}</td><td>{leader.best_score}</td><td>{leader.total_attempts}</td><td>{(leader.best_average_time_ms/1000).toFixed(1)} שנ׳</td><td>{new Date(leader.achieved_at).toLocaleDateString("he-IL")}</td></tr>)}</tbody></table>{!leaders.length&&<p>עדיין אין תוצאות להצגה.</p>}</section></>;
}
