"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import type { CSSProperties } from "react";
import { cleanExamText } from "../lib/exam-text";
type Leader={display_name:string;best_score:number;total_attempts:number;best_average_time_ms:number;achieved_at:string;position?:number};
type Question={id:string;question:string;subject:string;topic:string;options:{id:string;text:string}[];timeLimit:number;score:number;lives:number;bankSize:number};
type AnswerReview={message:string;score:number;lives:number;gameOver:boolean;question:string;selectedText?:string;correctAnswer:string;correctText:string;explanation:string};
type Result=AnswerReview&{totalTimeMs:number;averageTimeMs:number;personal:Leader&{position:number}};
function LifeMeter({lives}:{lives:number}){return <div className="streak-life-meter" aria-label={`${lives} מתוך 5 סימני חיים נותרו`}><div><span>סימני חיים</span><b>{lives}/5</b></div><div className="streak-life-icons">{Array.from({length:5},(_,index)=><span className={index<lives?"alive":"lost"} key={index}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 20.4 4.2 13A5.2 5.2 0 0 1 12 6.1 5.2 5.2 0 0 1 19.8 13Z"/></svg></span>)}</div></div>}
export function Leaderboard(){
  const[name,setName]=useState<string|null>(null),[leaders,setLeaders]=useState<Leader[]>([]),[personal,setPersonal]=useState<(Leader&{position:number})|null>(null),[error,setError]=useState(""),[question,setQuestion]=useState<Question|null>(null),[score,setScore]=useState(0),[lives,setLives]=useState(5),[time,setTime]=useState(60),[feedback,setFeedback]=useState(""),[selectedAnswer,setSelectedAnswer]=useState<string|null>(null),[answerWasCorrect,setAnswerWasCorrect]=useState<boolean|null>(null),[answerReview,setAnswerReview]=useState<AnswerReview|null>(null),[reviewPaused,setReviewPaused]=useState(false),[result,setResult]=useState<Result|null>(null),[locked,setLocked]=useState(false);
  const questionRef=useRef<Question|null>(null),lockedRef=useRef(false),nextTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null);
  const refresh=useCallback(async()=>{const response=await fetch("/api/leaderboard",{cache:"no-store"}),data=await response.json();setName(data.name);if(!response.ok){setLeaders([]);setPersonal(null);setError(data.error||"לא ניתן להתחבר כרגע לטבלת המצטיינים המשותפת.");return}setError("");setLeaders(data.leaders);setPersonal(data.personal)},[]);
  useEffect(()=>{const id=setTimeout(()=>void refresh(),0);return()=>clearTimeout(id)},[refresh]);
  useEffect(()=>()=>{if(nextTimerRef.current)clearTimeout(nextTimerRef.current)},[]);
  async function login(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),response=await fetch("/api/leaderboard/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),code:form.get("code")})}),data=await response.json();if(!response.ok)return setError(data.error);setError("");await refresh()}
  async function loadQuestion(restart=false){if(nextTimerRef.current){clearTimeout(nextTimerRef.current);nextTimerRef.current=null}const response=await fetch("/api/streak/question",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({restart})}),data=await response.json();if(!response.ok)return setError(data.error);questionRef.current=data;setQuestion(data);setScore(data.score);setLives(data.lives);setTime(data.timeLimit);setFeedback("");setSelectedAnswer(null);setAnswerWasCorrect(null);setAnswerReview(null);setReviewPaused(false);lockedRef.current=false;setLocked(false)}
  async function start(){if(nextTimerRef.current)clearTimeout(nextTimerRef.current);setResult(null);setAnswerReview(null);setReviewPaused(false);setLives(5);setError("");await loadQuestion(true)}
  function holdReview(){if(nextTimerRef.current){clearTimeout(nextTimerRef.current);nextTimerRef.current=null}setReviewPaused(true)}
  const submit=useCallback(async(selected:string)=>{const current=questionRef.current;if(!current||lockedRef.current)return;lockedRef.current=true;setLocked(true);setSelectedAnswer(selected);const response=await fetch("/api/streak/answer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({questionId:current.id,selected})}),data=await response.json();if(!response.ok){setError(data.error);setSelectedAnswer(null);lockedRef.current=false;setLocked(false);return}setAnswerWasCorrect(data.correct);setFeedback(data.message);setLives(data.lives);if(data.correct){setScore(data.score);nextTimerRef.current=setTimeout(()=>void loadQuestion(false),850);return}setAnswerReview(data);if(!data.gameOver){nextTimerRef.current=setTimeout(()=>void loadQuestion(false),6200);return}questionRef.current=null;setQuestion(null);setResult(data);setPersonal(data.personal);await refresh()},[refresh]);
  function choiceStyle(id:string):CSSProperties|undefined{if(!locked)return undefined;if(id===selectedAnswer&&answerWasCorrect)return{borderColor:"#27865f",background:"#e7f7ef",color:"#14573f",boxShadow:"inset 5px 0 #27865f"};if(id===selectedAnswer&&answerWasCorrect===false)return{borderColor:"#cf3c47",background:"#fff0f1",color:"#8e151e",boxShadow:"inset 5px 0 #cf3c47"};if(answerReview&&id===answerReview.correctAnswer)return{borderColor:"#27865f",background:"#e7f7ef",color:"#14573f",boxShadow:"inset 5px 0 #27865f"};return undefined}
  useEffect(()=>{if(!question||locked)return;const interval=setInterval(()=>setTime(value=>{if(value<=1){clearInterval(interval);void submit("");return 0}return value-1}),1000);return()=>clearInterval(interval)},[question,locked,submit]);
  if(!name)return <section className="leader-login"><span>מצטיין כיתתי</span><h1>כניסה למשחק הרצף</h1><form onSubmit={login}><label>שם הסטודנט/ית<input name="name" required/></label><label>קוד כניסה<input name="code" type="password" required inputMode="numeric"/></label>{error&&<p>{error}</p>}<button>כניסה</button></form></section>;
  return <><header className="leader-heading"><div><span>מחובר/ת: {name}</span><h1>מצטיין כיתתי</h1></div>{question?<div className="grid gap-2"><p className="m-0 text-center text-base font-black leading-snug text-[#a40f19]">משחק לאמיצים בלבד —<br/>אם למדת רק שיאצו, תברח מכאן!!!!!!!!</p><LifeMeter lives={lives}/></div>:<button onClick={start}>התחלת משחק רצף</button>}</header>
  {error&&<p className="database-notice" role="alert">{error}</p>}
  {question&&<section className="streak-game"><header><div className="streak-score"><b>רצף נוכחי: {score}</b><small>שיא אישי: {personal?.best_score??0} • מאגר {question.bankSize} שאלות</small></div><div className={`streak-timer ${time<=10?"urgent":""}`} style={{background:`conic-gradient(#b8141f ${time/question.timeLimit*360}deg,#f0e5e6 0deg)`}}><span><b>{time}</b><small>שניות</small></span></div></header><div className="streak-timebar"><i style={{width:`${time/question.timeLimit*100}%`}}/></div><span className="streak-topic">{cleanExamText(question.subject)}{question.topic!==question.subject?` • ${cleanExamText(question.topic)}`:""}</span><h2 dir="rtl">{cleanExamText(question.question)}</h2><div>{question.options.map(option=><button dir="rtl" disabled={locked} key={option.id} style={choiceStyle(option.id)} onClick={()=>submit(option.id)}><b>{option.id}</b><span>{cleanExamText(option.text)}</span></button>)}</div>{feedback&&<p className={`streak-feedback ${answerWasCorrect?"correct":"incorrect"}`}>{feedback}</p>}{answerReview&&!answerReview.gameOver&&<article className="streak-inline-review"><p>התשובה הנכונה: <strong>{answerReview.correctAnswer}. {cleanExamText(answerReview.correctText)}</strong></p><p><b>הסבר:</b> {cleanExamText(answerReview.explanation)}</p><small>{reviewPaused?"המעבר האוטומטי נעצר. אפשר לקרוא בנחת.":"השאלה הבאה תעלה בעוד שש שניות…"}</small><button className="mt-3 min-h-11 rounded-lg border-0 bg-[#a40f19] px-5 py-2 font-black text-white" type="button" onClick={reviewPaused?()=>void loadQuestion(false):holdReview}>{reviewPaused?"עבור לשאלה הבאה":"אל תעבור שאלה"}</button></article>}</section>}
  {result&&<section className="streak-end"><span className="streak-result-message">{result.message}</span><h2>הניקוד שלך בניסיון הזה: {result.score}</h2><article className="streak-answer-review"><small>השאלה שבה הסתיים הרצף</small><h3>{cleanExamText(result.question)}</h3><p>התשובה שלך: <b>{result.selectedText?cleanExamText(result.selectedText):"לא נענתה"}</b></p><p className="streak-correct-answer">התשובה הנכונה: <strong>{result.correctAnswer}. {cleanExamText(result.correctText)}</strong></p><p><b>הסבר:</b> {cleanExamText(result.explanation)}</p></article><div><button onClick={start}>נסי שוב</button><button onClick={()=>setResult(null)}>חזרה לטבלת המצטיינים</button></div></section>}
  <section className="leader-table"><table><thead><tr><th>מקום</th><th>שם</th><th>ניקוד</th><th>זמן ממוצע</th><th>תאריך</th></tr></thead><tbody>{leaders.slice(0,10).map((leader,index)=><tr className={leader.display_name===name?"current":""} key={`${leader.display_name}-${leader.achieved_at}-${index}`}><td>{["🥇","🥈","🥉"][index]||index+1}</td><td>{leader.display_name}</td><td>{leader.best_score}</td><td>{(leader.best_average_time_ms/1000).toFixed(1)} שנ׳</td><td>{new Date(leader.achieved_at).toLocaleDateString("he-IL")}</td></tr>)}</tbody></table>{!leaders.length&&<p>עדיין אין תוצאות להצגה.</p>}</section></>;
}
