import Foundation
import PDFKit

struct Line { let text:String; let x:CGFloat; let y:CGFloat }
func clean(_ value:String)->String{let result=value.unicodeScalars.filter{![0x202A,0x202B,0x202C,0x202D,0x202E,0x2066,0x2067,0x2068,0x2069].contains(Int($0.value))}.map(String.init).joined().trimmingCharacters(in:.whitespacesAndNewlines);return result.hasPrefix(". ") ? String(result.dropFirst(2)).trimmingCharacters(in:.whitespaces):result}
func lines(_ page:PDFPage)->[Line]{(page.selection(for:page.bounds(for:.mediaBox))?.selectionsByLine() ?? []).compactMap{selection in let raw=selection.string ?? "",text=clean(raw);guard !text.isEmpty else{return nil};let box=selection.bounds(for:page),shift=raw.contains(". ") ? 20.0:0;return Line(text:text,x:box.minX+shift,y:box.minY)}}
func number(_ text:String)->Int?{let value=text.replacingOccurrences(of:" ",with:"").replacingOccurrences(of:".",with:"");return Int(value)}
func grouped(_ source:[Line])->String{let groups=Dictionary(grouping:source){Int(round($0.y/3))};var value=groups.keys.sorted(by:>).map{key in groups[key]!.sorted{$0.x>$1.x}.map(\.text).joined(separator:" ")}.joined(separator:" ").replacingOccurrences(of:"  ",with:" ");for(pair)in[("הפ רעה","הפרעה"),("פתוח ים","פתוחים"),("הד ם","הדם"),("אי ז ","איזו "),("לב ה","הלב"),("עיים המ","המעיים")]{value=value.replacingOccurrences(of:pair.0,with:pair.1)};return value}
func answerMap(_ document:PDFDocument)->[Int:String]{guard let page=document.page(at:0)else{return[:]};let source=lines(page),labels=source.filter{$0.x<90&&["א","ב","ג","ד"].contains($0.text)};let marks=source.filter{$0.text.contains("X")&&$0.x>80&&$0.y<550};var result:[Int:String]=[:],seen=Set<String>();for mark in marks{guard let label=labels.min(by:{abs($0.y-mark.y)<abs($1.y-mark.y)}),abs(label.y-mark.y)<3 else{continue};let key="\(Int(mark.x)):\(Int(mark.y))";if seen.contains(key){continue};seen.insert(key);let start=label.x+30,local=Int(round((mark.x-start)/22.8))+1,question=local+(label.y<400 ? 20:0);if question>=1&&question<=30{result[question]=label.text}};return result}

guard CommandLine.arguments.count==5,let exam=PDFDocument(url:URL(fileURLWithPath:CommandLine.arguments[1])),let answers=PDFDocument(url:URL(fileURLWithPath:CommandLine.arguments[2])),let year=Int(CommandLine.arguments[3])else{fatalError("usage: extract-exam-bank exam.pdf answers.pdf year output.json")}
let manual:[Int:[String]]=[
  2015:["ב","ד","א","ד","א","ג","ב","ב","ג","ב","ד","א","א","ג","ד","ב","ב","ד","ד","ד","א","ב","ד","ג","ג","א","ג","א","ג","א"],
  2016:["ד","ג","ד","ב","ג","ג","א","א","ב","ד","ג","ג","ג","ג","א","ד","א","ג","א","ג","ד","א","ד","א","ב","ד","ד","ב","א","ב"]
]
let keys:[Int:String]=manual[year].map{Dictionary(uniqueKeysWithValues:$0.enumerated().map{($0.offset+1,$0.element)})} ?? answerMap(answers);print("Verified answer keys: \(keys.count)");var output:[[String:Any]]=[]
for pageIndex in 0..<exam.pageCount{guard let page=exam.page(at:pageIndex)else{continue};let source=lines(page);let markers=source.compactMap{line->(Int,Line)? in guard line.x>470,line.y>60,let n=number(line.text),n>=1,n<=30 else{return nil};return(n,line)}.sorted{$0.1.y>$1.1.y};for(index,item)in markers.enumerated(){let(n,marker)=item;guard let correct=keys[n]else{continue};let lower=index+1<markers.count ? markers[index+1].1.y+3:60;let region=source.filter{$0.y<=marker.y+3&&$0.y>lower&&$0.text != marker.text};let labels=region.filter{line in line.x>470&&["א","ב","ג","ד"].contains(line.text.replacingOccurrences(of:".",with:""))}.sorted{$0.y>$1.y};guard labels.count>=4 else{continue};let question=grouped(region.filter{$0.y>labels[0].y+3&&$0.x<470});var options:[[String:String]]=[];for optionIndex in 0..<4{let upper=labels[optionIndex].y+3,lowerOption=optionIndex+1<labels.count ? labels[optionIndex+1].y+3:lower;let text=grouped(region.filter{$0.x<470&&$0.y<=upper&&$0.y>lowerOption});options.append(["id":["א","ב","ג","ד"][optionIndex],"text":text])};if !question.isEmpty&&options.allSatisfy({!($0["text"] ?? "").isEmpty}){output.append(["id":"western-\(year)-\(n)","year":year,"subject":"רפואה מערבית","topic":"רפואה מערבית","questionNumber":n,"question":question,"options":options,"correctAnswer":correct,"explanation":"","source":"מבחן רפואה מערבית \(year)"])}}}
output.sort{($0["questionNumber"]as!Int)<($1["questionNumber"]as!Int)};let data=try JSONSerialization.data(withJSONObject:output,options:[.prettyPrinted,.withoutEscapingSlashes]);try data.write(to:URL(fileURLWithPath:CommandLine.arguments[4]));print("Extracted \(output.count) verified questions for \(year)")
